<a href="https://colab.research.google.com/github/Farhana-Tani/PyTorch-basics/blob/main/View_and_Reshape_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
tensor= torch.arange(12)

In [ ]:
reshaped_tensor_view=tensor.view(2,6)
reshaped_tensor_reshape=tensor.reshape(2,6)
print(reshaped_tensor_view)
print(reshaped_tensor_reshape)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


In [ ]:
reshaped_tensor_view=tensor.view(2,6)
reshaped_tensor_reshape=tensor.reshape(2,6)
print(reshaped_tensor_view)
print(reshaped_tensor_reshape)
print(reshaped_tensor_view.shape)
print(reshaped_tensor_reshape.shape)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
torch.Size([2, 6])
torch.Size([2, 6])


In [ ]:
tensor.is_contiguous()

True

In [ ]:
inferred_shape= tensor.view(3,-1)
print(inferred_shape)
print(inferred_shape.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


In [ ]:
inferred_shape= tensor.view(3,-1)
print(inferred_shape)
print(inferred_shape.shape)

mxn --> [1xM]

In [ ]:
tensor3d= torch.arange(24).reshape(2,3,4)
print(tensor3d)
print(tensor3d.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])


In [ ]:
flattened= tensor3d.view(-1)
print(flattened)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])


In [ ]:
flattened.is_contiguous()

True

In [ ]:
tensor2d= torch.arange(24).reshape(12,2)
transpose_tensor= tensor2d.t()

In [ ]:
transpose_tensor.is_contiguous()

False

In [ ]:
error = transpose_tensor.view(6,4)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [ ]:
error= transpose_tensor.reshape(6,4)

In [ ]:
print(error)
print(error.shape)

tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [ 1,  3,  5,  7],
        [ 9, 11, 13, 15],
        [17, 19, 21, 23]])
torch.Size([6, 4])


In [ ]:
contiguous= transpose_tensor.contiguous()
error= contiguous.view(6,4)

In [ ]:
print(error)
print(error.shape)

tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [ 1,  3,  5,  7],
        [ 9, 11, 13, 15],
        [17, 19, 21, 23]])
torch.Size([6, 4])
